FROM node:20.19.5-alpine3.22

WORKDIR /usr/src/app

# Copy package files first to leverage Docker cache
ADD package-lock.json package.json ./

# Install dependencies
RUN npm install && \
npm cache clean --force

#and now we copy the rest of the application files
COPY . .

# Expose the port that the application listens on.
EXPOSE 5000

# Run the application.
CMD ["node", "index.js"]