FROM ubuntu:22.04

WORKDIR /usr/src/app

COPY . .

# Updates apt cache (separate layer)
RUN apt-get update && \
apt-get install -y nodejs npm && \
npm install && \
apt-get autoremove --purge -y npm && \
apt-get clean && \
rm -rf /var/lib/apt/lists/*

# Expose the port that the application listens on.
EXPOSE 5000

CMD ["node", "index.js"]