# Stage 1: Build dependencies. Using dev variant
FROM docker/dhi-node:20.19.5-alpine3.22-dev AS build


WORKDIR /usr/src/app

# Copy package files first to leverage Docker cache
COPY package-lock.json package.json ./

# Install production dependencies only
RUN npm install && \
npm cache clean --force

# Copy the rest of the application files
COPY . .

# Stage 2: Production stage. No dev variant, no package manager
FROM docker/dhi-node:20.19.5-alpine3.22 AS production

WORKDIR /usr/src/app

# Copy only the necessary files from the build stage
COPY --from=build /usr/src/app/package.json ./
COPY --from=build /usr/src/app/node_modules ./node_modules
COPY --from=build /usr/src/app/index.js ./index.js

# Expose the port that the application listens on
EXPOSE 5000

# Run the application
CMD ["node", "index.js"]
